---
- name: Copy multiple Files with the same name to Remote Hosts in different directories.
  hosts: ansible_client
  become: yes
  tasks:

    - name: Read file mappings
      slurp:
        src: /data/file_mappings.txt
      register: file_mapping_result

    - name: Convert binary content to a string
      set_fact:
        decoded_content: "{{ file_mapping_result['content'] | b64decode }}"

    - name: Save decoded content to a file
      copy:
        content: "{{ decoded_content }}"
        dest: "{{ item.destination }}"
      loop: "{{ decoded_content | from_yaml }}"

    - name: Debug message before rsync
      debug:
        msg: "Copying file with rsync: {{ item.source }} to {{ item.destination }}"
      loop: "{{ decoded_content | from_yaml }}"

###########################################################################################################################################################################################################################
#### Create a txt file called for example "file_mappings.txt" 
#### NOTE !! Create it in yml, then convert into a txt, when you get errors, it is most likely that your txt file is not in the correct format####
#### LEAVE NO SPACES in the text or it will give errors. 
#### The inside format of the txt should be like this ####
#### - source: /home/TEST/CLOCKMGM.so
####   destination: /data/bad/CLOCKMGM.so
#### - source: /tmp/CLOCKMGM.so
####   destination: /data/1/CLOCKMGM.so
############################################################################################################################################################################################################################
