---
- name: jobids
  hosts: all
  vars:
    jobids: []
  tasks:
    - name: Task 1
      command: /bin/sleep 5
      when: ansible_hostname == 'ansible_client'
      async: 10
      poll: 0
      register: result1

    - name: Task 2
      command: /bin/sleep 5
      when: ansible_hostname == 'keolis'
      async: 10
      poll: 0
      register: result2

    - name: Capture Job IDs
      set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
      with_items: "{{ [ result1, result2 ] }}"

    - name: Show Job IDs
      debug:
        var: jobids

...
