---
- name: serial playbook
  hosts: all
  gather_facts: true
  serial:
    - 1
    - 2
  tasks:
   - name: Task1
     command: /bin/sleep 1

   - name: Task2
     command: /bin/sleep 2

   - name: Task3
     command: /bin/sleep 3

   - name: Task4
     command: /bin/sleep 4

...
